# fly.toml file generated for snapdropbd on 2023-03-23T15:47:12+06:00

app = "snapdropbd"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT="3000"
  DB_URL="mongodb+srv://Sajon:8nmtUkx6zBgTH4ub@thesisproject.uyrszo9.mongodb.net/snapdrop_db?retryWrites=true&w=majority"
  JWT_SECRET="plus est en vous"
  GOOGLE_CLIENT_ID="861084726957-9qcs9ivbphq1043ls2b2me5obfhk48ut.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET="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"
  FB_CLIENT_ID="1869465020092669"
  FB_CLIENT_SECRET="23fc0ee3cd008b03c5b086232aee42f8"
  MAPS_API_KEY="AIzaSyAhkieTsOpkBf6tw71b4Y2cUL4RTRasYGo"
  MAPS_API_SECRET="qwu5pDJXSlw13rG9OKqduNbVYns="
  CLOUDINARY_API_KEY="889273888131551"
  CLOUDINARY_NAME="djxuxbxet"
  CLOUDINARY_API_SECRET="JLSh56UtMiSmUPr604ZRWVRwMeU"
  PATHAO_BASE_URL="https://api-hermes.pathao.com"
  PATHAO_CLIENT_EMAIL="hello@projectcode.me"
  PATHAO_GRANT_TYPE="password"
  PATHAO_CLIENT_ID="7LDdwMra1Y"
  PATHAO_CLIENT_SECRET="zoIWeOgAXU1PzjIn7toBsuTRFUkaXqk97h7Ccs1e"
  PATHAO_CLIENT_PASSWORD="qoVQ871Mc"
  # BASE_FRONTEND_URL = "http://localhost:4200"
  BASE_FRONTEND_URL = "https://snap-drop.vercel.app"
  # BASE_BACKEND_URL = "http://localhost:3000"
  BASE_BACKEND_URL = "https://snapdropbd.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
